# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fakedata < Formula
  desc ""
  homepage "https://github.com/lucapette/fakedata"
  version "1.2.0"

  on_macos do
    url "https://github.com/lucapette/fakedata/releases/download/v1.2.0/fakedata_1.2.0_darwin_amd64.tar.gz"
    sha256 "a3a4b0bcb503b5f6157fbc5370be8908ab8c6aabea8c441192ba4ab3d2b69e9c"

    def install
      bin.install "fakedata"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Fakedata
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/lucapette/fakedata/releases/download/v1.2.0/fakedata_1.2.0_linux_amd64.tar.gz"
      sha256 "f3091a3b3e2cc6452ae54850a3aced0ed00ee1699417ca189436f16f3b9e6c50"

      def install
        bin.install "fakedata"
      end
    end
  end
end
