# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fakedata < Formula
  desc ""
  homepage "https://github.com/lucapette/fakedata"
  version "1.4.0"

  on_macos do
    url "https://github.com/lucapette/fakedata/releases/download/v1.4.0/fakedata_1.4.0_darwin_amd64.tar.gz"
    sha256 "0b138c86443cc4c7d2d81549adf4b8b447cc7844edc25600e98d05c77bd521d6"

    def install
      bin.install "fakedata"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Fakedata
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/lucapette/fakedata/releases/download/v1.4.0/fakedata_1.4.0_linux_amd64.tar.gz"
      sha256 "d357ed38acff533f97ec09656ca6ee49a1850d86af664cbb102fcb04e84def4f"

      def install
        bin.install "fakedata"
      end
    end
  end
end
